const config = require('./config.json5')

module.exports = {
  defaultSettings: {
    prefix: config.prefix,
    language: config.lang,
    notifyRep: config.notifyRep,
    banRep: config.banRep,
    antispam: true,
    banned: false,
    disable_purge: true,
    ignoredChannels: [],
    autorole: null,
    excludeLogging: '',
    invite: false,
    welcome_channel: null,
    welcome_message: null,
    mute: [],
    message_blacklist: [],
    blocked_role: [],
  },
  defaultBans: [],
  defaultUser: {
    rep: 0,
    bannedFromServer: [],
    bannedFromServerOwner: [],
    bannedFromUser: [],
    probes: [],
    reasons: [],
    username_changes: [],
  },
  commandList: [
    { 'cmd': 'help', 'args': ' [Command]' },
    { 'cmd': 'shutdown', 'args': ' [-f]' },
    { 'cmd': 'token', 'args': '' },
    { 'cmd': 'setprefix', 'args': ' <Prefix>' },
    { 'cmd': 'prefix', 'args': ' <Prefix>' },
    { 'cmd': 'ban', 'args': ' [<ID/Mentions/Name> <Reason> <Probe>]' },
    { 'cmd': 'unban', 'args': ' <ID/Mentions/Name> *Not recommended*' },
    { 'cmd': 'language', 'args': ' <ja/en>' },
    { 'cmd': 'setnotifyrep', 'args': ' <0...10>' },
    { 'cmd': 'setbanrep', 'args': ' <0...10>' },
    { 'cmd': 'antispam', 'args': '' },
    { 'cmd': 'antispam toggle', 'args': '' },
    { 'cmd': 'antispam disable', 'args': '' },
    { 'cmd': 'antispam enable', 'args': '' },
    { 'cmd': 'antispam ignore', 'args': ' <Channel>' },
    { 'cmd': 'antispam status', 'args': ' [Channel]' },
    { 'cmd': 'reload', 'args': '' },
    { 'cmd': 'setnick', 'args': ' <NewName> [User]' },
    { 'cmd': 'setnickname', 'args': ' <NewName> [User]' },
    { 'cmd': 'purge', 'args': ' [number/all]' },
    { 'cmd': 'purge gdel', 'args': '' },
    { 'cmd': 'purge gdel-msg', 'args': '' },
    { 'cmd': 'purge gdel-really', 'args': '' },
    { 'cmd': 'purge remake', 'args': ' <Channel>' },
    { 'cmd': 'togglepurge', 'args': ' [enable/disable]' },
    { 'cmd': 'dump', 'args': ' [guilds|users|channels|emojis|messages]' },
    { 'cmd': 'listemojis', 'args': ' [escape]' },
    { 'cmd': 'invite', 'args': ' [GuildID] [create] or [allow/deny]' },
    { 'cmd': 'role', 'args': ' <Role> [User]' },
    { 'cmd': 'autorole', 'args': ' [add/remove] <Role>' },
    { 'cmd': 'info', 'args': '' },
    { 'cmd': 'image', 'args': '' },
    { 'cmd': 'image anime', 'args': '' },
    { 'cmd': 'image', 'args': ' nsfw|r18' },
    { 'cmd': 'image custom', 'args': ' <subreddit>' },
    { 'cmd': 'didyouknow', 'args': ' <User:Guild> [:server]' },
    { 'cmd': 'lookup', 'args': ' <User>' },
    { 'cmd': 'status minecraft', 'args': '' },
    { 'cmd': 'status fortnite', 'args': '' },
    { 'cmd': 'encode', 'args': ' <String>' },
    { 'cmd': 'decode', 'args': ' <Base64String>' },
    { 'cmd': 'encrypt', 'args': ' <Text> <Password>' },
    { 'cmd': 'decrypt', 'args': ' <EncryptedText> <Password>' },
    { 'cmd': 'deletemsg', 'args': ' [User]' },
    { 'cmd': 'setignore', 'args': ' <Channel>' },
    { 'cmd': 'leave', 'args': '' },
    { 'cmd': 'instantban', 'args': ' <User>' },
    { 'cmd': 'instantkick', 'args': ' <User>' },
    { 'cmd': 'resetnick', 'args': ' [User]' },
    { 'cmd': 'serverinfo', 'args': '' },
    { 'cmd': 'setwelcome', 'args': ' [channel:message] [Channel:Message]' },
    { 'cmd': 'mute', 'args': ' <User>' },
    { 'cmd': 'banned', 'args': '' },
    { 'cmd': 'talkja', 'args': ' <話しかけたいこと(日本語のみ)>' },
    { 'cmd': 'releases', 'args': ' [Version]' },
    { 'cmd': 'eval', 'args': ' <Program>' },
    { 'cmd': 'blockrole', 'args': ' <Role>'},
  ],
}
